In [19]:
import torch

In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
from mha import muliheaded_attention

In [43]:
testing_mha=muliheaded_attention(4,2)

In [44]:
## Checking the module list output. We based on the number of heads we pass, we will have that many linear layers.
testing_mha.q_mapping

ModuleList(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

In [45]:
# A random tensor representing 1 image, 5 patches and embedding size of each patch to be 4
testing_tensor=torch.randn(1,5,4)
print(testing_tensor)
testing_mha(testing_tensor)

tensor([[[-0.0438,  0.2764, -0.3378,  0.3199],
         [ 0.2835,  1.4261, -0.3528, -0.6895],
         [-0.4506,  0.5400,  0.1213,  0.0595],
         [-1.3977,  0.3222,  0.2341,  0.5312],
         [ 0.1161,  0.1118, -1.2440, -0.4312]]])
torch.Size([5, 4])
torch.Size([5, 2])
tensor([[-0.0438,  0.2764],
        [ 0.2835,  1.4261],
        [-0.4506,  0.5400],
        [-1.3977,  0.3222],
        [ 0.1161,  0.1118]])
torch.Size([5, 2])
tensor([[-0.3378,  0.3199],
        [-0.3528, -0.6895],
        [ 0.1213,  0.0595],
        [ 0.2341,  0.5312],
        [-1.2440, -0.4312]])


### Output says that 2 heads will perform calculations on 5 patches where embedding size is 4. Since we have 2 heads, the embedding will be broken down into size of 2 and 2 for each head.