In [19]:
import torch

In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [79]:
from mha import muliheaded_attention

In [80]:
testing_mha=muliheaded_attention(4,2)

In [81]:
## Checking the module list output. We based on the number of heads we pass, we will have that many linear layers.
testing_mha.q_mapping

ModuleList(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

In [82]:
# A random tensor representing 1 image, 5 patches and embedding size of each patch to be 4
testing_tensor=torch.randn(2,5,4)
print(testing_tensor)
testing_mha(testing_tensor)

tensor([[[ 1.6022,  0.3741,  1.6797,  0.7351],
         [-1.9161,  0.1131,  0.0776, -0.5317],
         [ 0.5763, -0.5550,  2.0243,  0.4050],
         [ 0.1537, -0.4472,  0.0421, -1.8714],
         [-0.5185,  2.2315, -0.9516, -2.4721]],

        [[-1.1293, -0.7910,  0.7194, -0.3520],
         [ 0.7536,  0.6839, -0.8130,  0.0744],
         [-0.8604, -1.5326,  1.6219,  0.5150],
         [ 0.3501, -0.7384,  0.7053,  1.2816],
         [ 0.8611,  0.2857,  0.4982,  1.3929]]])
torch.Size([5, 4])
tensor([[0.6434, 0.3019],
        [0.3340, 0.3247],
        [0.5634, 0.3165],
        [0.5217, 0.3224],
        [0.4295, 0.3386]], grad_fn=<MmBackward0>)
tensor([[0.0693, 0.4810],
        [0.1540, 0.5581],
        [0.1785, 0.6021],
        [0.3732, 0.7872],
        [0.3834, 0.7905]], grad_fn=<MmBackward0>)
[tensor([[0.6434, 0.3019, 0.0693, 0.4810],
        [0.3340, 0.3247, 0.1540, 0.5581],
        [0.5634, 0.3165, 0.1785, 0.6021],
        [0.5217, 0.3224, 0.3732, 0.7872],
        [0.4295, 0.3386, 0.383

### Output says that 2 heads will perform calculations on 5 patches where embedding size is 4. Since we have 2 heads, the embedding will be broken down into size of 2 and 2 for each head.

In [55]:
import numpy as np